Composite dictionary
TheHsoa/CourseProject pull request #1
Opened 2018-01-17 10:56 UTC by TheHsoa

Реализуйте класс-коллекцию для хранения элементов, имеющих уникальный составной ключ [Id, Name] (Id и Name – компоненты ключа, могу быть произвольного типа).Предоставьте методы для добаления и удаления элементов, а так же методы для эффективного по скорости получения элементов по их Id или Name.Программа должна содержать пример использования коллекции с идентификатором ключа в виде пользовательского типа (т.е. Id в ключе – UserType, объекты UserType должны сравниваться по значению).Дополнительно: Создайте потокобезопасную реализацию этой коллекции (не использовать коллекции из пространства имён System.Collections.Concurrent).

2018-03-19 11:42 UTC, pomadin requested changes
Надо исправить ряд моментов.

2018-03-19 11:42 UTC, pomadin commented on UserTypes/UserTypeA.cs
> +    public class UserTypeA
где сравнение по значению для типов?

2018-03-19 11:42 UTC, pomadin commented on UserTypes/UserTypeB.cs
> +    public class UserTypeB
где сравнение по значению для типов?

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +        }
fail, подумай почему.

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +    public class CompositeDictionary<TId, TName, TValue> : IDictionary<CompositeKey<TId, TName>, TValue>
минор, но, надо было реализовать коллекцию, а словарь чуть более частный случай коллекции

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +        private readonly Dictionary<string, List<TValue>> idDictionary = new Dictionary<string, List<TValue>>();
в чем соль индекса через string?

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +        private readonly Dictionary<string, List<TValue>> idDictionary = new Dictionary<string, List<TValue>>();
почему нельзя поддержать классику Dictionary<TId, List<>>, почему нельзя поддержать классику Dictionary<TName, List<>>

2018-03-19 11:42 UTC, pomadin commented on UserTypes/UserTypeA.cs
> +            if (ReferenceEquals(this, obj)) return true;
при твоей реализации, лучше оставить эту проверку только в типизированном Equals, иначе выглядит как повторение

2018-03-19 11:42 UTC, pomadin commented on UserTypes/UserTypeB.cs
> +            if (ReferenceEquals(this, obj)) return true;
аналогично типу A

2018-03-19 11:42 UTC, pomadin commented on UserTypes/UserTypeB.cs
> +    public class UserTypeB : IEquatable<UserTypeB>
ради справки: формально, для реализации сравнения по значению - нужно только GetHashCode/Equals(object), реализация IEquatable<> -  полезна, но не обязательна

2018-03-19 11:42 UTC, pomadin commented on UserTypes/UserTypeB.cs
> +    public class UserTypeB : IEquatable<UserTypeB>
одного примера достаточно было кстати

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeKey.cs
> +            return EqualityComparer<TId>.Default.Equals(Id, other.Id) && EqualityComparer<TName>.Default.Equals(Name, other.Name);
это не совсем корректно, какой EqualityComparer использовать это внешнее знание, то есть или мы работаем напрямую с объектом и его equals, либо просим предоставить EqualityComparer, но реализацию при его непередаче должна быть, имхо

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeKey.cs
> +                return (EqualityComparer<TId>.Default.GetHashCode(Id) * 397) ^ EqualityComparer<TName>.Default.GetHashCode(Name);
аналогично Equals

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +        public ICollection<CompositeKey<TId, TName>> Keys => fullDictionary.Keys;
оба метода (GetKeys/GetValues) возвращают обертки над текущим словарем

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +        public ICollection<CompositeKey<TId, TName>> Keys => fullDictionary.Keys;
они кстати публичные и не обернуты в read/write lock

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +            var dictionaryKeyValuePairs = fullDictionary.Select(keyValue =>
так Select() вроде лишний

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +            }
и тут ToArray вроде достаточно перед CopyTo

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +                return nameDictionary[name];
надо отдавать копию

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +                return nameDictionary.TryGetValue(name, out values);
надо отдавать копию

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +                return idDictionary[id];
надо отдавать копию

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +                return idDictionary.TryGetValue(id, out values);
надо отдавать копию

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +            return TryGetValue(new CompositeKey<TId, TName>(id, name), out value);
надо отдавать копию

2018-03-19 11:42 UTC, pomadin commented on Dictionary/CompositeDictionary.cs
> +                return fullDictionary.TryGetValue(key, out value);
надо отдавать копию

2018-03-19 11:42 UTC, pomadin commented on Program.cs
>  ﻿using System;
а зачем main, если есть тесты?

2018-03-19 11:42 UTC, pomadin commented on Tests/CompositeDictionaryTests.cs
> +﻿using System;
тесты не смотрел ;)

2018-03-19 11:50 UTC, TheHsoa commented on Dictionary/CompositeDictionary.cs
> +            var dictionaryKeyValuePairs = fullDictionary.Select(keyValue =>
Возможено стоит переделать и возвращать dictionaryKeyValuePairs.GetEnumerator()

2018-03-21 03:55 UTC, TheHsoa commented on Dictionary/CompositeDictionary.cs
> +        public ICollection<CompositeKey<TId, TName>> Keys => fullDictionary.Keys;
Заметил, когда переписывал в ICollection
Обернул Count

2018-03-22 05:51 UTC, pomadin commented
Ну теперь вроде все терпимо стало. 😉

2018-03-22 05:59 UTC, merged